export const PAGE_HOME = 'PAGE_HOME';
export const PAGE_LOGIN = 'PAGE_LOGIN';
export const PAGE_ABOUT = 'PAGE_ABOUT';
export const PAGE_NUTRITION_GUIDE = 'PAGE_NUTRITION_GUIDE';

export const PAGE_RECIPES_BY_CATEGORY = 'PAGE_RECIPES_BY_CATEGORY';
export const PAGE_RECIPES = 'PAGE_RECIPES';
export const PAGE_MEAL_TYPE = 'PAGE_MEAL_TYPE';
export const PAGE_DIETARY_RESTRICTION = 'PAGE_DIETARY_RESTRICTION';
export const PAGE_FAVORITES = 'PAGE_FAVORITES';
export const PAGE_MEAL_PLANNER = 'PAGE_MEAL_PLANNER';


export const HOME_PAGE_RECIPE_LIMIT = 8;